---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: imageuseslatesttag
  spec:
    template:
      spec:
        containers:
          - name: bar
            image: quay.io/redhat-cop/openshift-applier:latest
